### ISSUE TITLE
V_0.1 review

### ISSUE THREAD

**Issue by Alejandro7c** [FranBurgos/TFG#57]
Basically, I obtain the following message every time I try to do something (save variable, show help, load   configuration...)

![bug1](https://user-images.githubusercontent.com/17246893/50701722-eeb76280-104e-11e9-8484-c45144c66286.PNG)

I suppose some file/s needed to execute the program properly is missing.

**Comment by FranBurgos** [comment]
I think that the problem rests on the paths that the code is using. I was using relative paths but they aren´t working properly.

**Comment by clopezno** [comment]
Are you using system environment properties?
See this [code example](https://docs.microsoft.com/en-us/dotnet/api/system.environment.currentdirectory?view=netframework-4.7.2)

**Comment by FranBurgos** [comment]
I think so, I´m trying packaging the application thou.

**Comment by FranBurgos** [comment]
I fixed the issue adding the folders needed to run the application. I updated the release V_0.1, then you could check the functionality whenever you want ;-).
