### ISSUE TITLE
V_0.1 Review 2

### ISSUE THREAD

**Issue by dsarabiad** [FranBurgos/TFG#58]
See attached some comments about V 0.1.

[Pruebas ReleaseV_0.1.docx](https://github.com/FranBurgos/TFG/files/2754967/Pruebas.ReleaseV_0.1.docx)

**Comment by FranBurgos** [comment]
[Pruebas.ReleaseV_0.1_revisado.docx](https://github.com/FranBurgos/TFG/files/2765454/Pruebas.ReleaseV_0.1_revisado.docx)
Some bugs don´t appear on my lap, maybe it´s a dll lack problem.
@dsarabiad @Alejandro7c
